### ISSUE TITLE
これ文字列内で展開しないでも、いいのではないでしょうか？

### ISSUE THREAD

**Issue by aznalo** [advancing-life/rabbit-can-backend#2]
https://github.com/advancing-life/rabbit-can-backend/blob/250bf178aaeb29b27fecc22c4b1e2791a2b550df/user.rb#L6

**Comment by flmil** [comment]
それ俺も思ってたw
`u_id:SecureRandom.hex(32), `
これで動くっしょ?

**Comment by aznalo** [comment]
![LGTM](http://i.giphy.com/uNSkyDeCoK4Q8.gif)
